# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f946c036cefe8ab091d99d7c917d6df7652e64b1334d3656ed479ca1dcd01196e09740d54d77dfea30a5e4bd31dca1656948e6e937ecf5563a5adc4f54b55811

test:
  secret_key_base: 02aeaa25a93de3f5a6fbef6bbf5677f048d0b9e6c2f5109cfdf72f81c552ca4eb5efcffa2da6b2cfa3491643427fbb70f9792649b3d42461dfd44e519a08a9be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
